### ISSUE TITLE
Implicit @RegexBuilder

### ISSUE THREAD

**Issue by filip-sakel** [kodlian/SwiftRegexDSL#1]
The `body` property in the `Regex` protocol can be annotated with `@RegexBuilder` so that conforming types implicitly get a regex-built body.

**Comment by kodlian** [comment]
Thank you, this is very convenient and cleaner. Updated in https://github.com/kodlian/SwiftRegexDSL/commit/a7511962a1a7f824720ff438c59e4106f40ea2a4
