### ISSUE TITLE
'Digit' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by dirk68-work** [kodlian/SwiftRegexDSL#4]
using the following code in a test app, importing the SwiftRegexDSL Package does not work

```Swift
import SwiftRegexDSL

struct Number:Regex{
    var body: Regex{
        Digit()
            .oneOrMore()
    }
}
```

and results in the following compiler error:
`'Digit' initializer is inaccessible due to 'internal' protection level`

[Default initializers in Swift are declared internal](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html#ID21) and can't be accessed from outside the package.

Unfortunately this means you have to manually add a public memberwise initializer to all structs using a default one now (digit is only **one** example)

**Comment by kodlian** [comment]
fixed in latest master
